### ISSUE TITLE
[Plan] 프로젝트 아이디어 기획

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/project-plan#1]
### 📌 Description
12월 28일(목) 아이디어 1차 회의를 위해 간단한 아이디어를 작성합니다. 
아이디어는 간단한 수준이라도 다다익선!!
SKT 사업 부문에서 사용할만한 아이디어도 좋지만, 우선은 생각의 제한을 두지 않고 생각해봅시다. 

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 다양한 아이디어 수집
  - 각자 생각한 아이디어를 아래 탬플릿을 활용하여 Comment 추가
  - 다른 사람이 생각한 아이디어를 보고 추가하고 싶은 의견이 있을 경우 Comment 추가
- 아이디어 구체화(28일-오프라인회의)
  - 아이디어 공유
  - 마인드맵 등을 활용하여 아이디어 구체화
  - 진행해보고 싶은 아이디어 우선순위 설정

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [x] 사전준비
  - [x] 팀 전체에 아이디어 작성 요청 📅 2023-12-26 @robert-min 
  - [x] 아아디어 작성 📅 2023-12-28
  - [x] 아이디어 구체화를 위한 방법 준비 📅 2023-12-28 @robert-min 

------

## 1. 아이디어 템플릿 양식
- 아래 양식을 복사해서 사용해주세요!!
- 아래 양식으로 작성이 어려울 시 자유 양식도 가능합니다.

```
## 아이디어 명

### 1. 내용
- 

### 2. 키워드
- 

### 3. 참고 링크
- 

```

**Comment by robert-min** [comment]
## (예시)인테리어를 위한 vision 인테리어 시뮬레이션 

### 1. 내용
- 인테리어를 미리 체험하고 디자인 확인을 위해서 공간을 인식하고 원하는 디자인을 그 공간에 맞게 배치할 수 있는 서비스 

### 2. 키워드
- vision, LLM

### 3. 참고 링크
-

**Comment by robert-min** [comment]
## 혼자 사는 어르신들을 위한 vision - 대화 bot

### 1. 내용
- 문제 : 혼자 사는 어르신들은 보호자들이 없어 위험 상황에 대응이 어렵고, 말동무가 없어 외로움
- AI 스피커를 활용해 위와 같은 문제를 해결한 사례도 존재 [1]
- 다만 기존의 AI 스피커는 사용자가 직접 호출했을 때만, 커뮤니케이션이 있어 어르신의 말동무 역할을 하기에 어려움은 물론 위험 상황에 대응 시에도 마찬가지로 어려움이 존재
- 독거 노인의 안전 사고 예방을 위해 자식이 부모님 집 거실에 CCTV를 놓거나 카메라를 설치하는 경우가 점차 늘어남에 따 카메라를 활용하여 위의 문제를 해결하고자 함
- 제안
  - 카메라 모션 인식을 통해 독거 노인 분들의 위험 상황을 인지하여 119 호출 등의 기능 제공
  - 장을 보거나, 식사를 하는 등의 상황을 인식하여 이와 관련된 대화 주제를 bot이 제공
  - 채팅 봇과 함께한 대화 내용을 정리하여 보호자에게 전송(가족인데 개인 정보에 문제가 있으려나?)


### 2. 키워드
- Vision, 대화 bot

### 3. 참고 링크
- [쓰러진 독거노인 생명 구한 AI 스피커...](https://www.chemicalnews.co.kr/news/articleView.html?idxno=7231) [1]

**Comment by chanyoungP** [comment]
## 시각장애인을위한 보행 보조 시스템

### 1. 내용

- 문제 : 시각 장애인들의 경우 위험물을 지팡이 또는 다른 기기로 인지하고 있지만, 시시각각 변화하는 상황에 유연하게 대처하기 어려움이 있음.
- 다른 기기들(휠체어[1], 소형 기기[2])를 활용하여 위험물 감지하는 기기들이 있지만, 따로 구매해야하는 비용이 발생함.
- 장애인과 같은 사회적 소외 계층에 대한 인식, 대우 들이 좋아짐에 따라서 소외계층을 위한 AI 서비스가 필요함
- 제안
    - 핸드폰 카메라를 통해서 거리의 상황을 인식 및 안내 음성을 통해 사용자에게 인지
    - 시시각각 변화하는 상황과 갑작스러운 위험상황 노출로부터 안전하게 거리를 걸어다닐 수 있는 기대 효과

### 2. 키워드

- Vision, LLM, 음성,

### 3. 참고 링크

- https://www.lifein.news/news/articleView.html?idxno=13806 [1]
- https://www.irobotnews.com/news/articleView.html?idxno=21667 [2]

**Comment by chanyoungP** [comment]
## 버츄얼 아바타 생성 AI

### 1. 내용

- 문제 : VR 시장에서 가상 아바타는 필수적이다. 하지만, 퀄리티 좋은 아바타를 착용하기 위해서는 수백만원에 상당하는 비용으로 주문을 해야하는 문제가 있다.
- VR 시장이 발전함에 따라서 메타버스에서의 문화 컨텐츠 역시 발전하고 있다.
- 따라서, VR 아바타를 쉽게 생성할 수 있는 생성 모델이 있을 경우, 기존의 점유하고 있던 시장에서 쉽고 빠르게 공급을 할 수 있을 것으로 기대된다.
- 또한 메타버스에서는 캐릭터 뿐만 아니라 공간(맵)도 중요한 요소이고 디자인에 있어서 시간과 비용이 많이 소요된다.
- 제안
    - 카메라 인식 또는 레퍼런스 이미지를 기반으로 VR 캐릭터 또는 map 생성 AI

### 2. 키워드

- Vision, 2D → 3D, 물리엔진

### 3. 참고 링크

- https://youtu.be/TWgwpymS3q8

**Comment by chanyoungP** [comment]
## 내 손안에 요약 유튜버 

### 1. 내용 
- 영화 요약 유튜버, 드라마 유튜버들이 큰 인기를 끌고 있음.
- 컨텐츠 생산자 입장에서 영화나 드라마를 모두 보고 분석해야하기 때문에 컨텐츠 생산 소모 시간 비용이 큼. 

### 2. 키워드
- vision, video, LMM, 

### 3. 참고 링크
- 없음

**Comment by kangdeokseo** [comment]
## 문화재 AI 가이드 - 문화재에 대한 해석

### 1. 내용

- 문제: 초·중학교의 문화재 교육 실태 조사 결과 학교 현장에서의 문화재 교육이 전반적으로 부실로 인해, 문화재 인식이 부족한 상황이다.
- 최근에도 10대 남녀가 경복궁 낙서를 훼손하는 등, 거주지 내 문화재에 대한 보존성 의식이 부족.- 기존 VQA기반 모델이나 VLM의 경우,  글로벌 건축물이나 전시 작품에만 높은 정확도로 Answer을 출력하기 때문에 한국 문화재 맞춤형 모델이 필요
- [[국내 최초 문화유산 유사사진을 검색해주는 ‘문화유산 찾아-zoom’ 정식 공개](https://news.bbsi.co.kr/news/articleView.html?idxno=3134628)] 등 국내 문화 유산에 대한 AI 활용 방안이 늘어가고 있음.
- 실제 정확도를 높이기 위한 방안으로 이미지를 통해 검색 엔진을 활용할 수 있는 ‘Bing AI’의 api와 구글 이미지 검색 api 등 third-party api에 대한 고려도 생각
- 제안
    - VLM fine-tuning을 위한 모델 선정(Beit3 or Llava…) 및 [[데이터](https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=&topMenu=&aihubDataSe=data&dataSetSn=71389)](AI허브 디지털 k-art) 전처리
    - 이미지 데이터를 통해 구글 이미지에 대한 정확한 명칭 제공
    - 이미지 데이터에 대한 문화적 배경, 설명 기능 제공
    - VLM 채팅 봇을 활용하여 문화재에 대한 인공지능의 주관적 평가 제시

### 2. 키워드

- VLM(Vision Langauge Model), 생성모델

### 3. 참고 링크

- 텍스트 하이퍼링크 참고

**Comment by heehminh** [comment]
## 에이닷과의 채팅을 기반으로 만든 노래 생성 AI

### 1. 내용

- 개인화 컨텐츠 (자신만의 커스텀할 수 있는 컨텐츠)
- 그 날 나의 하루 일과를 바탕으로 나만의 노래 생성 (멜로디만 할지 가사도 넣을지는 추후 고민해봐야함)
- 에이닷과의 채팅이 아니여도 됨 (일기탭을 만들어서 일기를 작성하거나 카톡같은 메신저에서 대화를 캡쳐해서 텍스트로 인식하거나 자신의 하루일과를 볼 수 있다면 어떤 형태의 텍스트든지 가능)
- 제안
    - input: text → output: music 생성 AI

### 2. 키워드

- 생성모델, TTS(는 아닌데 뭔가 애매.. Text-to-Music)

### 3. 참고 링크

- OpenAI - MuseNet https://openai.com/research/musenet
- Google - Magenta https://github.com/magenta/magenta
- VEED.IO (AI Music Generator) https://www.veed.io/tools/ai-music-generator

**Comment by kimdoeon** [comment]
움직이는 엽서
---
### 1. 내용

- 배경/필요성: 최근 AI 졸업사진, AI 프로필 등 젊은층을 대상으로 __재미있는 AI 컨텐츠__ 인기, 나만의 감성 추구 시대 / 정적인 사진에 움직임을 부여하여 소중한 순간을 특별하게 기억 또는 공유(SNS)할 수 있게 됨.
- 문제 : 웹서비스로 모바일에선 접근성이 떨어짐
- 사진 -> 비디오 변환 과정에서 원본 사진이 가진 고유한 감성이 사라짐.  (사진보다는 애니메이션 느낌)
- 전체 사진이 비디오로 변환됨. 세부 설정x
- 제안
    - img -> video 변환시 화질 유지(최대한 원본 사진과 동일하게)
    - 사용자가 움직임 부여하고 싶은 부분 선택 가능하게

### 2. 키워드
multimodal, 생성모델, img-to-video

### 3. 참고 링크
- [Stable Video Diffusion](https://arstechnica.com/information-technology/2023/11/stability-ai-releases-stable-video-diffusion-which-turns-pictures-into-short-videos/)
- [gen2](https://research.runwayml.com/gen2)
- [meta](https://makeavideo.studio/)

**Comment by kimdoeon** [comment]
지체 장애인 음성 인식 모델
---
### 1.내용
- 문제:  지체장애인은 청각장애인과 달리 말하는 것과 몸을 움직이는 데 어려움을 겪어 의사소통이 쉽지 않음. 최근 AI 스피커와 같은 음성 인식 서비스를 사용하기 어려움.
- 대상: 지체 장애인(등급 등에 따라 구체화 필요)
- 제안
   - STT 파인튜닝. 모델, [데이터](https://aihub.or.kr/aihubdata/data/view.do?currMenu=115&topMenu=100&aihubDataSe=realm&dataSetSn=608) 선정.   
   - [skt 발달장애 행동분석 기술](https://news.sktelecom.com/199471)과 연관 지을 수도.?

### 2. 키워드
장애인 보조공학, STT

### 3. 참고자료
[소보로](https://blog.testworks.co.kr/customer_case_sovoro/)
[언어장애인 음성 문장 인식 알고리즘 비교 논문](https://manuscriptlink-society-file.s3-ap-northeast-1.amazonaws.com/sma/conference/sma2020fall/presentation/36.pdf)

**Comment by chanyoungP** [comment]
## 파일 포맷 자동 변환

### 1. 내용
- 파일 포맷별로 호환 여부 갈라지고, 글자 형식 깨지는 것이 불편
- 호환 변환 프로그램이 있지만, 별도 설치를 해야하는 문제가 있고, 유료인 부분도 많음
- 따라서 문서를 스캔(이미지로)보고 원하는 형식으로 바꿔주는 프로그램이 필요할 수 있다고 봄 

### 2. 키워드
- vision - image to text ....

### 3. 참고 링크
- 급 생각이라 없음

**Comment by chanyoungP** [comment]
## 이미지에서 멀리 있는 객체를 정확하게 바꿔주는 AI 

### 1. 내용
- 일종의 연구 또는 챌린지라고 생각해서 ... 
- 이미지에서 굉장히 작게 또는 멀리 찍힌 객체를 인식해서 그를 원래 사이즈 또는 클리어한 사이즈로 변환해주는 기능
- 응용 서비스는 생각해봐야함 

### 2. 키워드
- vision, 화질 개선 등등

### 3. 참고 링크
-
