### ISSUE TITLE
[Plan] 아이디에이션 - AI Family

### ISSUE THREAD

**Issue by robert-min** [FLYAI4/project-plan#4]
### 📌 Description
AI Family

1. 문제
- 부모가 없으시거나 혼자 사는 자취생이 가족으로부터 느낄 수 있는 유대감을 느낄 수 없다.
- 넥타이, 면도 등 일상에서 어른들에게 배울 수 있는 삶의 지식을 얻을 수 없다.
2. 제안
- AI Family(부모?)를 통해 사용자가 유대감을 느낄 수 있는 서비스를 제공하자
- 본인의 얼굴을 기반으로 부모의 얼굴을 생성하여 홈패드 등에 콘텐츠로 제공(생성 ai)
- 캘린더와 연동하여 일정에 따라 사용자에게 대화를 제공
  - ex). 캘린더에 다음날 면접이면, 면접 준비 잘 했는지 물어봐줌
  - 이전의 AI스피커가 사용자가 질문을 하면 답변해주는 정도면, 캘린더나 vision 등을 활용해 먼저 질문을 해주거나 대화를 제공하는 서비스
- 기술
  - 음성, 이미지, 모션 인식, 표정 인식 등

<br>

### 🎈 Goal
<p>$\tiny{구체적인\ 산출물을\ 포함한\ 목표를\ 작성해주세요.}$</p>

- 아래 가이드를 활용하여 아이디어 리서치를 진행합니다.
- 리서치 가이드에 있는 질문을 짧더라도 최대한 추가해주세요.
- 리서치 할 때 참고한 링크(출저)를 작성해주세요.

<br>

### ✏️ Todo
<p>$\tiny{목표\ 달성을\ 위해\ 해야할\ 일을\ 세부적으로\ 작성해주세요.}$</p>

- [ ] 아이디어 리서치 진행 📅 2024-01-02
- [ ] 리서치 내용 공유 📅 2024-01-02

------

## 1. 아이디어 리서치 가이드
💡 아이디어 우선순위 선정 이후 리서치를 진행할 때, 도움이 될만한 가이드를 작성해봤습니다.
아이디어 리서치는 결국 ‘내가’ 생각한 아이디어를 설득하는 것이기 때문에, 꼭 리서치 가이드 항목을 따라서 작성할 필요는 없지만, 어떤 내용을 조사해야할지 모를 때, 가이드를 참고하세요 

가이드 항목 이외에도 좋은 아이디어임을 보여줄 내용들을 조사하면 됩니다.

<br>

🔑 프로젝트를 위한 프로젝트를 하지말자 (기술만 쓰는 프로젝트, 문제 해결이 없는 프로젝트)
- 항상 문제를 해결하는 것에 초점을 맞추고 해결을 위한 도구로 인공지능을 사용한다는 의미 
- 서비스에서의 문제는 (문제 대상의 대한 정의, 문제 대상이 무엇을 필요로 하는가) 
- `Problem`
- `Needs`

<br>

1. **문제 정의 및 필요성:**
    - 어떤 현실적인 문제를 해결하고자 하는가?
    - 해당 문제가 실제로 존재하며 중요한가?
2. **비슷한 서비스 및 경쟁 분석:**
    - 이미 비슷한 아이디어나 서비스가 있는가?
    - 경쟁 서비스들은 어떤 특징을 가지고 있으며, 여러분의 아이디어는 어떻게 다를 것인가?
3. **비즈니스 모델:**
    - 프로젝트를 어떻게 상업화할 것인가?
4. **기술적 측면:**
    - 어떤 기술을 사용하여 프로젝트를 구현할 것인가?
5. **기존 연구 및 논문 리뷰:**
    - 관련된 분야의 최근 연구 동향이나 논문을 조사(Abstract까지만 봐도 좋습니다)
6. **기술적인 도전과제:**
    - 프로젝트를 구현하는 동안 어떤 기술적인 도전과제가 예상되는가?
    - 이 도전과제를 어떻게 극복할 수 있는가?
7. **데이터:**
    - 프로젝트를 위한 충분한 양의 데이터가 있는가?
    - 데이터의 품질은 어떤가? 라벨링이 되어 있는가?
    - 데이터를 수집하여 진행이 가능한가?
8. **고민거리들**…
    - 각 아이디어마다 생각했던 고민거리들을 어떻게 해결할 수 있을지 생각해보자

### 아래 템플릿을 복사해서 활용해주세요!!

```
### 1. **문제 정의 및 필요성:**


### 2. **비슷한 서비스 및 경쟁 분석:**


### 3. **비즈니스 모델:**


### 4. **기술적 측면:**


### 5. **기존 연구 및 논문 리뷰:**


### 6. **기술적인 도전과제:**


### 7. **데이터:**


### 8. **고민거리들**…


### 9. 출처
- 

```

**Comment by robert-min** [comment]
## (작성중)

### 1. **문제 정의 및 필요성:**
시장 상황
- 2022년 기준 1인가구 비율 34.5%로 매년 점차 늘어가는 추세

![스크린샷 2024-01-01 오후 10 38 37](https://github.com/FLYAI4/project-plan/assets/91866763/644e9bdb-0449-4524-a1d5-a21ead482d16)


- 1인 가구의 사회적 고립 외로움 문제 - (1)

문제
- 1인 가구가 증가함에 따라 여러 어려움이 존재 - (2)
	- 균형 잡힌 식사를 하기 어려움 (42.4%)
	- 아프거나 위급할 때 혼자서 대처하기 어려움 (30.9%)
	- 식사준비, 주거관리 등을 하기 어렵다. (25%)
	- 나를 부양해주는 가족이 없어 경제적으로 불안하다. (19.5%)
	- 다른 사람들로부터 고립되어 있어 외롭다. (18.3%)

필요성
- 1인 가구의 사회적 고립(외로움)을 해결하고자 대화 등의 상호작용을 통해 유대감을 형성

서비스
- 사용자의 여러 정보(vision, 캘린더 등)를 활용하여 먼저 상호작용할 수 있는 AI 서비스 제공
	- 기존 AI스피커보다 좀 더 적극적인 커뮤니케이션이 가능하도록
- 공감, 정보제공 등 사용자와 대화를 할 수 있는 콘텐츠를 서비스가 먼저 제공

### 2. **비슷한 서비스 및 경쟁 분석:**


### 3. **비즈니스 모델:**



### 4. **기술적 측면:**


### 5. **기존 연구 및 논문 리뷰:**


### 6. **기술적인 도전과제:**


### 7. **데이터:**


### 8. **고민거리들**…
- 비슷한 서비스를 AI스피커로 하기에는 너무 큰 범위이고 비즈니스 모델도 문제가 있음
- 어플로 생각하려면 콘텐츠를 구체화할 필요가 있음


### 9. 출처
- [# 1인가구의 외로움과 사회적 고립 및 정신건강 문제의 특성과 유형: 서울시 1인가구를 중심으로](https://www.kihasa.re.kr/hswr/v.42/4/127/1%EC%9D%B8%EA%B0%80%EA%B5%AC%EC%9D%98+%EC%99%B8%EB%A1%9C%EC%9B%80%EA%B3%BC+%EC%82%AC%ED%9A%8C%EC%A0%81+%EA%B3%A0%EB%A6%BD+%EB%B0%8F+%EC%A0%95%EC%8B%A0%EA%B1%B4%EA%B0%95+%EB%AC%B8%EC%A0%9C%EC%9D%98+%ED%8A%B9%EC%84%B1%EA%B3%BC+%EC%9C%A0%ED%98%95+%EC%84%9C%EC%9A%B8%EC%8B%9C+1%EC%9D%B8%EA%B0%80%EA%B5%AC%EB%A5%BC+%EC%A4%91%EC%8B%AC%EC%9C%BC%EB%A1%9C) - (1)
- [1인가구 문제 통계청](https://n.news.naver.com/mnews/article/346/0000048131) - (2)

**Comment by kimdoeon** [comment]
### 1. **문제 정의 및 필요성:**
* [자립준비 청년들에게 가장 필요한건 믿을만한 어른과의 유대다. → 현실적으로 쉽지 않음 → 극단적 선택으로 이어짐](https://www.joongang.co.kr/article/25148388#home)
* 자립준비 청년에게 현실적 조언이나 사회적 적응에 도움을 줄 수 있는 **인적 네트워크** 부족
* 인적 자원, 사회 지지 체계 부족으로 이를 대체할 수 있는 디지털 기술이 필요함
* [직접 지원(생활비, 주거시설) 외 심리적, 감정적으로 의지할 대상 없음](https://m.segye.com/view/20230912515828)
* 사람과의 유대를 기계를 통해 극복한 사례 존재
    * [소셜 로봇 지역사회 노인 우울 개선](https://www.khanews.com/news/articleView.html?idxno=225586)
    * [외로움을 달래주는 AI 기반 앱](https://stock.mk.co.kr/news/view/140216)
    * [독거노인,AI스피커와 ‘정서적 대화’ 일반인의 3배](https://m.khan.co.kr/it/it-general/article/201907091657001#c2b)
### 2. **비슷한 서비스 및 경쟁 분석:**
* 이미 비슷한 아이디어나 서비스가 있는가?
  - ‘Dadvice 유튜브 아빠’
  - 디지털 기반 자립준비청년 정서 관리 서비스 지원→ AI스피커 심리 상담
* 경쟁 서비스들은 어떤 특징을 가지고 있으며, 여러분의 아이디어는 어떻게 다를 것인가?
   - Dadvice : 유튜브 영상을 통한 단방향 소통으로 유대감 형성과는 거리가 있음
   - AI스피커 : 실제 정서적 정서적 유대감 효과 확인. 그러나 __‘부모’를 대체 가능할만한가에 대한 의문__. 주로 질문에 대한 답으로 대화가 이루어짐.
  * 차별성 ⇒ 양방향 소통을 가능하게 하고, 부모 이미지까지 제공해 자립준비청년 맞춤형 서비스 제공
 
### 3. **비즈니스 모델:**
- 프로젝트를 어떻게 상업화할 것인가?
    - B2C : 자립준비 청년들 또는 정서적 유대감이 필요한 사람
    - B2B : 자립준비 청년들을 지원하는 지자체 또는 복지 재단

### 4. **기술적 측면:**
* 어떤 기술을 사용하여 프로젝트를 구현할 것인가?
  * 자식 얼굴로 부모 얼굴 생성할 수 있는 모델 - [styleGan](https://github.com/NVlabs/stylegan)
   ⇒ 얼굴의 다양한 특징(나이,성별 등)들이 분리되어 각각의 특징별 컨트롤을 통해 이미지 변환
   ⇒ 자연스럽고 고화질의 이미지 생성
  * STT- [whisper api](https://platform.openai.com/docs/guides/speech-to-text)
  * 텍스트 생성 - [chatGPT api](https://platform.openai.com/docs/guides/text-generation)
    ⇒ 일상 속 팁, 삶의 지식 제공 특화되도록
    ⇒ 일정 연동 기반 대화 제공하도록
  * 부모 얼굴 이미지 기반 실시간 아바타 생성과 음성 합성 -  [Heygen: v2 api](https://docs.heygen.com/docs/transform-your-photo-into-real-time-speech-with-v2-api)
    ⇒ 사진, 텍스트 → 음성변환(이미지기반 가상 음성 생성)

### 5. **기존 연구 및 논문 리뷰:**
* [소비자-인공지능 기기의 상호작용 요인에 대한 질적 연구](https://accesson.kr/kscap/assets/pdf/15487/journal-21-1-21.pdf)
⇒ 사용자와 AI 스피커의 상호작용에 영향을 미치는 요인 분석
⇒ 인간이 정서적 측면에서 AI 스피커에게 요구하는 특성 파악 가능

### 6. **기술적인 도전과제:**
- 프로젝트를 구현하는 동안 어떤 기술적인 도전과제가 예상되는가?
    - 사용자가 거부감을 느끼지 않을만큼 자연스러운 AI human을 구현 가능한가?
    - 자식으로부터 부모 얼굴 생성
- 이 도전과제를 어떻게 극복할 수 있는가?
    - styleGan을 활용

### 7. **데이터:**
   
### 8. **고민거리들**…
- AI가 ‘부모’를 대체함으로써 생기는 사용자와 AI의 유대감이 무너졌을 때 발생하는 부작용을 어떻게 감당할 것인지..
- 장비 지원 여부(태블릿, 스피커)
- [인공지능이 사람처럼 행동하는 게 바람직한가에 대한 고민.](https://dbr.donga.com/article/view/2102/article_no/10969/ac/a_view)
 → 사용자가 지나치게 몰입함으로 인한 부작용
 → BUT 챗봇이 고객에게 인공지능임을 밝혔을 경우 구매율 감소
- [인간의 사물을 의인화하는 경향을 악용할 가능성](https://www.digitaltoday.co.kr/news/articleView.html?idxno=491248)

**Comment by heehminh** [comment]
### 1. **문제 정의 및 필요성**

- 1인가구 급증과 함께 외로움, 사회적 고립
    
    https://www.si.re.kr/node/66227
    
- 자립을 준비하는 청년들 - 정서적으로 의지할 대상 없음
    
    https://www.kyeonggi.com/article/20230507580194
    
- 부모가 있음에도,  상처받은 경우 다수
    
    https://www.asiae.co.kr/article/2019022300503247649
    

### 2. **비슷한 서비스 및 경쟁 분석:**

- 이미 비슷한 아이디어나 서비스가 있는가?
    - Youtube How to DAD: https://www.youtube.com/@HowtoDad
    - 챗봇 ‘워봇 (Woebot)’
        
        https://www.chosun.com/site/data/html_dir/2017/08/25/2017082502644.html 
        
        매일 사용자에게 먼저 메시지를 보냄, 낮은 자유도의 챗봇, 사용자의 채팅에 대하여 미리 프로그래밍된 범위에서의 답변만을 제시하여 챗봇의 인격화 제어 
        
    - 챗봇 ‘쿠키 (KUKI)’
        
        https://www.arkthinker.com/ko/ai-tools/kuki-ai/
        
        (유료) 음성채팅기능
        
        AI의 아바타가 있음  
        
    - 빅스비 루틴 (사용자의 활용 패턴을 분석 or 본인이 등록): https://www.samsungsvc.co.kr/solution/23738
- 경쟁 서비스들은 어떤 특징을 가지고 있으며, 여러분의 아이디어는 어떻게 다를 것인가?
    - STT, TTS를 통한 양방향 소통, 모션 인식과 표정 등 실감나는 소통을 기반으로 한 정서적 지원
    - 기존 AI 스피커보다 적극적인 대화 제공

### 3. **비즈니스 모델:**

- 자립을 준비하는 청년 정서적 지원 (자립준비청년 지원 강화를 위한 보호서비스의 필요성)

### 4. **기술적 측면:**

- 얼굴 생성 AI
- STT https://github.com/sooftware/kospeech
- 텍스트 생성 ChatGPT
- TTS or TTA
    - TTS: https://cloud.google.com/text-to-speech?hl=ko (구글 TTS, 목소리 설정 가능)
    - TTA: https://github.com/suno-ai/bark
- 모션 인식

### 5. **기존 연구 및 논문 리뷰:**

### 6. **기술적인 도전과제:**

### 7. **데이터:**

### 8. **고민거리들:**

- 챗봇 ‘일라이자’ → 일라이자 효과: 기계와 소통하는 데 지나치게 몰입한 나머지 기계에 인격을 부여하는 현상 (기사에 언급한 챗봇과 다른 챗봇인데 우연히 이름이 일치함)
    
    https://www.sisain.co.kr/news/articleView.html?idxno=50121
    
- AI 챗봇은 사용자가 인공지능과 상호작용하고 있음을 명확히 알려줘야 한다. (이유: 사용자들이 인공지능에 지나치게 몰입해서 생기는 혼란으로 인한 부작용을 막기 위해서) → ‘유대’를 중심으로 한 인공지능을 만들어도 되는지..

**Comment by robert-min** [comment]
> 키워드만 적어서 따로 정리X -> 아이디어 리서치로 한 부분은 위의 내용 확인
> 유대감을 타깃으로 할 수 없어졌기 때문에 현실적으로 진행이 어려울 것으로 판단 => 이슈 종료 합니다.


# 240102 - 아이디어 결정 회의 기록

## AI Family


AI에 유대감을 가지면 안됨 - 사회적, 문제가 됨

챗봇을 만들 때, 윤리X


생성형 모델
- 음성 + 아바타가 이야기하는 것 처럼(실시간으로)
- 정보
	- 일상 속 팁(일상 속의 데이터)
	- 서비스에 비해 제공하는 것이 작은 부분
	- 일상의 루틴(빅스비 루틴) - 루틴으로 등록하면 알림으로 제공하는
- AI 스피커
	- 실제 혼자사는 사람에게 지원 했을 때, 효과는 있음 ex)독거노인
	- 효과는 있지만 차별성을 어떻게?

비즈니스
- B2C : 자립 청년한테 파는 느낌.
- B2G : 청소년 자립 대상으로 하는 사업


쿠키
- 챗봇 - 텍스트
- 유료화 - 음성

유대를 빼고 정보제공를 제공 -> 텍스트 기반

워봇?
- 우을증 환자 타겟으로 하는
- 사용자에게 매일 메시지를 보내 -> 회사에서 만드는 답변(의무? 규제? 윤리 순회, 표준)

AI + 사람 유대 사례는 있음 -> 어떻게하면 상호작용을 잘할지 논문 자료
노인을 대상으로 했을 때는 괜찮, 하지만 우리 타깃으로 했을 때는 역효과
